server:
  port: 8329

agent-config:
  org-id: "1234"
  client-id: "lvm-lab"
  vm-id: "tent-env1"
  agent-id: "123445"
  monitor:
    mount-points:
      - "/mnt/machines/c1-vm-1"
      - "/tmp"

metrics:
  backend:
    base-url: "http://localhost:3117"
    api-key: ""

agent:
  agent-version: 1.0.2
  last-atomic-number-seen: 0
  poll-interval-ms: 10000