server:
  port: 8329

agent-config:
  org-id: "default"
  client-id: "default"
  vm-id: "default"
  agent-id: "default"
  monitor:
    mount-points:
      - "/tmp"

metrics:
  backend:
    base-url: "http://localhost:3117"
    api-key: ""

agent:
  agent-version: 1.0.3
  last-atomic-number-seen: 0
  poll-interval-ms: 10000